//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSD_Project.App.Pages
{


    public partial class HandleOrders
    {

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new PSD_Project.App.Pages.Main Master
        {
            get
            {
                return ((PSD_Project.App.Pages.Main)(base.Master));
            }
        }
    }
}
